#!/usr/bin/perl -w
# Copyright (c) 2016 SUSE LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

=head1 boilerplate

boilerplate - boilerplate code for perl scripts

=head1 SYNOPSIS

boilerplate [OPTIONS] FILE

=head1 OPTIONS

=over 4

=item B<--help, -h>

print help

=back

=head1 DESCRIPTION

lorem ipsum ...

=cut

use strict;
use Data::Dump;
use YAML::Tiny;
use Getopt::Long;
Getopt::Long::Configure("no_ignore_case");

my %options;

sub usage($) {
	my $r = shift;
	eval "use Pod::Usage; pod2usage($r);";
	if ($@) {
		die "cannot display help, install perl(Pod::Usage)\n";
	}
}

GetOptions(
	\%options,
	"verbose|v",
	"help|h",
) or usage(1);

usage(1) unless @ARGV;
usage(0) if ($options{'help'});

my $yaml = YAML::Tiny->read('scenario-definitions.yaml');
for my $file (@ARGV) {
	$file =~ /(?:.*\/)?(?<distri>[^.]+)\.(?<arch>[^-]+)-(?<version>[^-]+)-(?<flavor>kvm-and-xen-sdboot)-Build(?<build>.*)\.qcow2$/;
	my $distri = lc $+{'distri'};
	my $arch = $+{'arch'};
	my $version = $+{'version'};
	my $flavor = $+{'flavor'};
	my $build = $+{'build'};
	my $product;
	my $h = $yaml->[0]->{'products'};
	for my $k (keys %{$h}) {
		my $p = $h->{$k};
		next unless ($p->{'distri'} eq $distri);
		next unless ($p->{'arch'} eq $arch);
		next unless ($p->{'flavor'} eq $flavor);
		$product = $k;
		last;
	}
	die "ERROR: $file: unknown product\n" unless $product;

	$h = $yaml->[0]->{'job_templates'};
	for my $k (keys %{$h}) {
		my $t = $h->{$k};
		next unless ($t->{'product'} eq $product);
		my $m = $yaml->[0]->{'machines'}->{$t->{'machine'}};
		my %vars = (BACKEND => $m->{'backend'}, %{$m->{'settings'}}, %{$t->{'settings'}||{}});
		print "./run $file ", join(' ', map { "$_=$vars{$_}" } sort keys %vars), "\n";
	}
}
